export const categories = [
  {
    id: 1,
    name: "All",
    color: "#FF0000",
    label: false,
  },
  {
    id: 2,
    name: "Unread",
    color: "#00FF00",
    label: false,
  },
  {
    id: 3,
    name: "Groups",
    color: "#FF00FF",
    label: false,
  },
  {
    id: 4,
    name: "Starred",
    color: "#FFFF00",
    label: true,
  },
  {
    id: 5,
    name: "Lead",
    label: true,
    color: "lightblue",
    label: true,
  },
  {
    id: 6,
    name: "Project",
    color: "#FFA500",
    label: true,
  },
];

export const chats = [
    {
      id: 1,
      name: "React Native Noob to Pro ⚛️",
      profilePic: "https://www.google.com/imgres?q=react&imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2Fa%2Fa7%2FReact-icon.svg%2F1200px-React-icon.svg.png&imgrefurl=https%3A%2F%2Fde.wikipedia.org%2Fwiki%2FReact&docid=3lreiOxoHjnzgM&tbnid=gaYKxV5AiW9dTM&vet=12ahUKEwiUzJvmjcOLAxVI1wIHHYVHCxoQM3oECBcQAA..i&w=1200&h=1068&hcb=2&ved=2ahUKEwiUzJvmjcOLAxVI1wIHHYVHCxoQM3oECBcQAA",
      lastMessage: 'You reacted 👍 to "NO Java this week"',
      lastMessageDatetime: "12:00 PM",
      unreadMessages: 2,
      image: null,
      group: true,
      icon: "group",
      community: false,
      single: false,
      isPinned: true,
      isMuted: false,
    },
    {
      id: 2,
      name: "Shweng Kings 👑",
      lastMessage: "You: Deleted this message",
      lastMessageDatetime: "Yesterday",
      unreadMessages: 2,
      image: null,
      group: true,
      icon: "group",
      community: false,
      single: false,
      isPinned: true,
      isMuted: false,
    },
    {
      id: 3,
      name: "Me",
      lastMessage: "You: Meeting tomorrow at 10 AM",
      lastMessageDatetime: "1/20/25",
      unreadMessages: 0,
      image: null,
      group: false,
      community: false,
      single: true,
      icon: "person",
      isPinned: true,
      isMuted: false,
    },
    {
      id: 4,
      name: "FET Official Group - L500 ✅",
      lastMessage: "Okonkwo: I have a meeting tomorrow at 10 AM",
      lastMessageDatetime: "1/20/25",
      unreadMessages: 0,
      image: null,
      group: false,
      community: false,
      single: true,
      icon: "person",
      isPinned: false,
      isMuted: false,
    },
    {
      id: 5,
      name: "Tech Enthusiasts 💻",
      lastMessage: "Alice: Let's discuss the new framework",
      lastMessageDatetime: "10:30 AM",
      unreadMessages: 3,
      image: null,
      group: true,
      icon: "group",
      community: false,
      single: false,
      isPinned: false,
      isMuted: true,
    },
    {
      id: 6,
      name: "Family Group 👨‍👩‍👧‍👦",
      lastMessage: "Mom: Don't forget the dinner tonight",
      lastMessageDatetime: "Yesterday",
      unreadMessages: 1,
      image: null,
      group: true,
      icon: "group",
      community: false,
      single: false,
      isPinned: false,
      isMuted: false,
    },
    {
      id: 7,
      name: "Alice",
      lastMessage: "You: Project deadline is next week",
      lastMessageDatetime: "7:29 PM",
      unreadMessages: 0,
      image: null,
      group: false,
      community: false,
      single: true,
      icon: "person",
      isPinned: false,
      isMuted: false,
    },
    {
      id: 8,
      name: "Bro",
      lastMessage: "You: Let's play at 8 PM",
      lastMessageDatetime: "8:00 AM",
      unreadMessages: 5,
      image: null,
      group: false,
      icon: "person",
      community: false,
      single: true,
      isPinned: false,
      isMuted: true,
    },
    {
      id: 9,
      name: "Book Club 📚",
      lastMessage: "Sarah: Next book is '1984' by George Orwell",
      lastMessageDatetime: "1/17/25",
      unreadMessages: 0,
      image: null,
      group: true,
      icon: "group",
      community: false,
      single: false,
      isPinned: false,
      isMuted: false,
    },
    {
      id: 10,
      name: "Fitness Freaks 💪",
      lastMessage: "Tom: Gym session at 7 AM tomorrow",
      lastMessageDatetime: "1/16/25",
      unreadMessages: 2,
      image: null,
      group: true,
      icon: "group",
      community: false,
      single: false,
      isPinned: false,
      isMuted: false,
    },
    {
      id: 11,
      name: "Travel Buddies ✈️",
      lastMessage: "Emma: Planning a trip to Bali",
      lastMessageDatetime: "1/15/25",
      unreadMessages: 0,
      image: null,
      group: true,
      icon: "group",
      community: false,
      single: false,
      isPinned: false,
      isMuted: true,
    },
    {
      id: 12,
      name: "Music Lovers 🎵",
      lastMessage: "Chris: New album released today",
      lastMessageDatetime: "1/14/25",
      unreadMessages: 1,
      image: null,
      group: true,
      icon: "group",
      community: false,
      single: false,
      isPinned: false,
      isMuted: false,
    },
    {
      id: 13,
      name: "Study Group 📖",
      lastMessage: "Laura: Exam on Monday, don't forget",
      lastMessageDatetime: "1/13/25",
      unreadMessages: 0,
      image: null,
      group: true,
      icon: "group",
      community: false,
      single: false,
      isPinned: false,
      isMuted: false,
    },
    {
      id: 14,
      name: "Photography Club 📸",
      lastMessage: "Anna: Photo walk this weekend",
      lastMessageDatetime: "1/11/25",
      unreadMessages: 0,
      image: null,
      group: true,
      icon: "group",
      community: false,
      single: false,
      isPinned: false,
      isMuted: true,
    },
  ];
