export const categories = [
  {
    id: 1,
    name: "All",
    color: "#FF0000",
    label: false,
  },
  {
    id: 2,
    name: "Unread",
    color: "#00FF00",
    label: false,
  },
  {
    id: 3,
    name: "Groups",
    color: "#FF00FF",
    label: false,
  },
  {
    id: 4,
    name: "Starred",
    color: "#FFFF00",
    label: true,
  },
  {
    id: 5,
    name: "Lead",
    label: true,
    color: "lightblue",
    label: true,
  },
  {
    id: 6,
    name: "Project",
    color: "#FFA500",
    label: true,
  },
];

export const chats = [
  {
    id: 1,
    name: "React Native Noob to Pro ⚛️",
    profilePic:
      "https://cdn.freebiesupply.com/logos/large/2x/react-1-logo-png-transparent.png",
    lastMessage: 'You reacted 👍 to "NO Java this week"',
    lastMessageDatetime: "12:00 PM",
    unreadMessages: 0,
    group: true,
    icon: "group",
    community: false,
    single: false,
    isPinned: true,
    isMuted: false,
  },
  {
    id: 2,
    name: "Shweng Kings 👑",
    profilePic:
      "https://yt3.ggpht.com/a/AATXAJyP-VdnMoptz81qg7j2uMVFFx92WdEtcsnEOA=s900-c-k-c0xffffffff-no-rj-mo",
    lastMessage: "~ShwengMan: Na lie",
    lastMessageDatetime: "Yesterday",
    unreadMessages: 74,
    group: true,
    icon: "group",
    community: false,
    single: false,
    isPinned: true,
    isMuted: false,
  },
  {
    id: 3,
    name: "Me",
    lastMessage: "Meeting tomorrow at 10 AM",
    lastMessageDatetime: "1/20/25",
    profilePic:
      "https://pbs.twimg.com/profile_images/1878509554893209600/x16Ea2HH_400x400.jpg",
    unreadMessages: 0,
    group: false,
    community: false,
    single: true,
    icon: "person",
    isPinned: true,
    isMuted: false,
  },
  {
    id: 4,
    name: "FET Official Group - L500 ✅",
    lastMessage: "Okonkwo: I have a meeting tomorrow at 10 AM",
    lastMessageDatetime: "1/20/25",
    unreadMessages: 0,
    group: false,
    community: false,
    single: true,
    icon: "group",
    isPinned: false,
    isMuted: false,
  },
  {
    id: 5,
    name: "Tech Enthusiasts 💻",
    profilePic:
      "https://cdn1.tnwcdn.com/wp-content/blogs.dir/1/files/2014/03/database-servers.jpg",
    lastMessage: "Alice: Let's discuss the new framework",
    lastMessageDatetime: "10:30 AM",
    unreadMessages: 3,
    group: true,
    icon: "group",
    community: false,
    single: false,
    isPinned: false,
    isMuted: true,
  },
  {
    id: 6,
    name: "The NKWIS 👨‍👩‍👧‍👦",
    profilePic:
      "https://images.rawpixel.com/image_png_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTA4L3Jhd3BpeGVsX29mZmljZV8xOV8zZF9lbW9qaV9zdHlsZV9vZl9mYW1pbHlfaXNvbGF0ZWRfb25fd2hpdGVfYl82ODdiY2M2My00ZTU1LTRjZmYtOWMyMi05M2YxOGVjODA3ZmYucG5n.png",
    lastMessage: "Mom: Don't forget the dinner tonight",
    lastMessageDatetime: "Yesterday",
    unreadMessages: 1,
    group: true,
    icon: "group",
    community: false,
    single: false,
    isPinned: false,
    isMuted: false,
  },
  {
    id: 7,
    name: "Alice",
    profilePic:
      "https://www.clipartkey.com/mpngs/m/163-1633105_alice-in-wonderland-alice-falling.png",
    lastMessage: "You: Project deadline is next week",
    lastMessageDatetime: "7:29 PM",
    unreadMessages: 0,
    group: false,
    community: false,
    single: true,
    icon: "person",
    isPinned: false,
    isMuted: false,
  },
  {
    id: 8,
    name: "Bro",
    lastMessage: "You: Let's play at 8 PM",
    lastMessageDatetime: "8:00 AM",
    unreadMessages: 5,
    group: false,
    icon: "person",
    community: false,
    single: true,
    isPinned: false,
    isMuted: true,
  },
  {
    id: 9,
    name: "Cloud",
    profilePic:
      "https://mobilemarketingwatch.com/wp-content/uploads/2016/04/cloud.jpg",
    lastMessage: "Next book is '1984' by George Orwell",
    lastMessageDatetime: "1/17/25",
    unreadMessages: 0,
    group: true,
    icon: "person",
    community: false,
    single: false,
    isPinned: false,
    isMuted: false,
  },
  {
    id: 10,
    name: "Fitness Freaks 💪",
    profilePic:
      "https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg?cs=srgb&dl=action-athlete-barbell-841130.jpg&fm=jpg",
    lastMessage: "Tom Brody: Gym session at 7 AM tomorrow",
    lastMessageDatetime: "1/16/25",
    unreadMessages: 2,
    group: true,
    icon: "group",
    community: false,
    single: false,
    isPinned: false,
    isMuted: false,
  },
  {
    id: 11,
    name: "Travel Buddies ✈️",
    lastMessage: "Emma: Planning a trip to Bali",
    lastMessageDatetime: "1/15/25",
    unreadMessages: 0,
    group: true,
    icon: "group",
    community: false,
    single: false,
    isPinned: false,
    isMuted: true,
  },
  {
    id: 12,
    name: "Music Lovers 🎵",
    lastMessage: "Chris: New album released today",
    lastMessageDatetime: "1/14/25",
    unreadMessages: 1,
    group: true,
    icon: "group",
    community: false,
    single: false,
    isPinned: false,
    isMuted: false,
  },
  {
    id: 13,
    name: "Study Group 📖",
    lastMessage: "Laura: Exam on Monday, don't forget",
    lastMessageDatetime: "1/13/25",
    unreadMessages: 0,
    group: true,
    icon: "group",
    community: false,
    single: false,
    isPinned: false,
    isMuted: false,
  },
  {
    id: 14,
    name: "Photography Club 📸",
    lastMessage: "Anna: Photo walk this weekend",
    lastMessageDatetime: "1/11/25",
    unreadMessages: 0,
    group: true,
    icon: "group",
    community: false,
    single: false,
    isPinned: false,
    isMuted: true,
  },
];
